"""update

Revision ID: dd3266ff0379
Revises: 6c7a8ae10f06
Create Date: 2024-12-03 20:56:24.729449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3266ff0379'
down_revision: Union[str, None] = '6c7a8ae10f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('MaxVolume', sa.Integer(), nullable=False), schema='my_app_schema')
    op.add_column('ships', sa.Column('MaxWeight', sa.Integer(), nullable=False), schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'MaxWeight', schema='my_app_schema')
    op.drop_column('ships', 'MaxVolume', schema='my_app_schema')
    # ### end Alembic commands ###
